### ISSUE TITLE
Storage model

### ISSUE THREAD

**Issue by sio** [pianohacker/secretgarden#1]
Kudos on this project, a very good idea!

Can you confirm that I understand the storage model correctly?

- All data is stored on local filesystem. There is no client-server architecture.
- All secret values are encrypted with a key based on user's SSH key. That means that different users can never share a secret.

If my cursory understanding is correct, this looks like an Ansible Vault++ :+1:

**Comment by pianohacker** [comment]
Sorry I missed this issue. Yes, you understand perfectly. It's designed for very small-scale secret generation/storage.

**Comment by sio** [comment]
Thanks!
